#!/bin/bash
#About this script

clear
echo -e ""
echo -e ""
echo -e ":::::::::  :::::::::: :::::::::  :::::::::::"
echo -e ":+:    :+: :+:        :+:    :+: :+:     :+:"
echo -e "+:+    +:+ +:+        +:+    +:+        +:+ "
echo -e "+#+    +:+ +#++:++#   +#++:++#+        +#+  "
echo -e "+#+    +#+ +#+        +#+    +#+      +#+   "
echo -e "#+#    #+# #+#        #+#    #+#     #+#    "
echo -e "#########  ########## #########      ###    "
echo -e ""
echo -e "MysticVPN" 
echo -e ""
echo -e ""
echo -e "For Debian 7 32 bit & 64 bit"
echo -e "For VPS with KVM and VMWare virtualization"
echo -e ""
echo -e "Original script by :"
echo -e "* Fornesia"
echo -e "* Rzengineer"
echo -e "* Fawzya"
echo -e ""
echo -e "Modded and Translated by _Dreyannz_"
echo -e "Edited by MysticVPN"
echo -e ""
echo -e "https://www.facebook.com/groups/mysticvpn/"
echo -e ""
